language: python
python:
  - 2.7
  - 3.6
  - 3.7
  - 3.8
before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - conda init bash
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
install:
  - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION libblas liblapack numpy cython ipopt future six setuptools sphinx numpydoc pkg-config
  - conda activate test-env
before_script:
  - conda info
  - conda list
  - pip --version
  - pip freeze
  - ls -al "$HOME/miniconda/lib/pkgconfig"
script:
  # Make sure the library installs.
  - python setup.py install
  - python -c "import ipopt"
  - python test/examplehs071.py
  - python test/exception_handling.py
  - python test/lasso.py
  - conda install scipy
  - python test/rosen.py
  # Make sure the docs build.
  - cd doc && make html && cd ..
