name: build

on: push

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build wheels on Windows with Ipopt binaries
    runs-on: windows-latest
    env:
      IPOPTVERSION: 3.14.19
      IPOPTARCH: win64-msvs2022-md
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Download Ipopt
        run: Invoke-WebRequest -Uri "https://github.com/coin-or/Ipopt/releases/download/releases%2F${{ env.IPOPTVERSION }}/Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}.zip" -OutFile "Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}.zip"

      - name: Extract Ipopt
        run: 7z x Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}.zip
      
      - name: Move Ipopt files
        run: mv Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}/* .

      - name: List files for debugging
        run: dir

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.2

      - name: Build wheels
        env:
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_SKIP: cp36-* cp37-* cp38-*
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cyipopt-wheels
          path: ./wheelhouse/*.whl