name: build_wheels

on: [push, pull_request]

# cancels prior builds for this workflow when new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_wheels:
    name: Build ${{ matrix.python }} on Windows
    runs-on: windows-latest
    env:
      IPOPTVERSION: 3.14.19
      IPOPTARCH: win64-msvs2022-md
    strategy:
      fail-fast: false
      matrix:
        python: [cp39, cp310, cp311, cp312, cp313, cp314]
    steps:
      - uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Download Ipopt
        run: Invoke-WebRequest -Uri "https://github.com/coin-or/Ipopt/releases/download/releases%2F${{ env.IPOPTVERSION }}/Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}.zip" -OutFile "Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}.zip"

      - name: Extract Ipopt
        run: 7z x Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}.zip
      
      - name: Move Ipopt files
        run: mv Ipopt-${{ env.IPOPTVERSION }}-${{ env.IPOPTARCH }}/* .

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.4.1 delvewheel

      - name: Build wheels
        env:
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_BUILD: ${{ matrix.python }}-*
        run: python -m cibuildwheel --output-dir wheelhouse

      - name: Repair wheels with delvewheel
        run: |
          mkdir wheelhouse_repaired
          delvewheel repair wheelhouse\*.whl --add-path "${{ github.workspace }}\bin" --wheel-dir wheelhouse_repaired

      - name: Upload intermediate wheels
        uses: actions/upload-artifact@v6
        with:
          name: wheels-${{ matrix.python }}
          path: ./wheelhouse_repaired/*.whl

  combine_wheels:
    name: Combine wheels into single artifact
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - name: Download all intermediate wheels
        uses: actions/download-artifact@v6
        with:
          pattern: wheels-*
          path: all_wheels
          merge-multiple: true 

      - name: Upload final combined artifact
        uses: actions/upload-artifact@v6
        with:
          name: cyipopt-wheels
          path: all_wheels/*.whl